Add a lock to avoid errors due to concurrent writes on streams map
We saw a fatal error during a cluster rollout where too many clients
were querying the server at the same time:
```
 fatal error: concurrent map writes
```
Adding a lock to safely do reads/writes on the map